const Map<String, String> arEg = {
  'WelcomeBack': 'اهلا بعودتك',

  'login': 'تسجيل الدخول',
  'email': 'البريد الإلكتروني',
  'phone': 'رقم الهاتف',
  'password': 'كلمة المرور',
  'or': 'أو',
  'RememberMe': 'تذكرني',
  'ForgotPassword': 'نسيت كلمة المرور ؟',
  'invalidEmail': 'صيغة بريد إلكتروني غير صحيحة',
  'enterPassword': 'الرجاء إدخال كلمة المرور',
  'shortPassword': 'يجب أن تكون كلمة المرور 8 أحرف على الأقل',
  'dontHaveAccount': 'ليس لديك حساب ؟',
  'Signup': "إنشاء حساب",
  'ConfirmAccount': "تنشيط حساب",
  'register': 'تسجيل',
  'enterName': 'الرجاء إدخال الاسم',
  'name': 'الاسم',
  'alreadyHaveAccount': 'لديك حساب بالفعل؟',
  'registeredSuccessfully': 'تم التسجيل بنجاح!.',
  'logout': 'تسجيل الخروج',
  'Basics': 'الأساسية',
  "dashboard": "لوحة التحكم",
  'orders': 'طلباتي',
  'savedCars': 'المحفوظة',
  'newCars': 'سيارات جديدة',
  'Compare': 'المقارنة',
  'about': 'المزيد عنا',
  'Settings': 'الإعدادات',
  'ThemeMode': 'تغيير المظهر',
  'Language': 'اللغة',
  'EditProfile': 'تعديل حسابي',
  'SignOut': 'تسجيل الخروج',
  "Home": "رئيسية",
  "Used": "مستعمل",
  "Sell": "بيع",
  "Imported": "مستورد",
  "More": "المزيد",
};
