const Map<String, String> arEg = {
  'WelcomeBack': 'مرحبًا بعودتك',
  'login': 'تسجيل الدخول',
  'email': 'البريد الإلكتروني',
  'phone': 'رقم الهاتف',
  'password': 'كلمة المرور',
  'or': 'أو',
  'RememberMe': 'تذكرني',
  'ForgotPassword': 'هل نسيت كلمة المرور؟',
  'invalidEmail': 'صيغة البريد الإلكتروني غير صحيحة',
  'enterPassword': 'يرجى إدخال كلمة المرور',
  'shortPassword': 'كلمة المرور يجب أن تكون 8 أحرف على الأقل',
  'dontHaveAccount': 'ليس لديك حساب؟',
  'Signup': 'إنشاء حساب',
  'ConfirmAccount': 'تأكيد الحساب',
  'register': 'لنبدأ التسجيل',
  'name': 'الاسم',
  'alreadyHaveAccount': 'هل لديك حساب بالفعل؟',
  'registeredSuccessfully': 'تم التسجيل بنجاح!',
  'loggedSuccessfully': 'تم تسجيل الدخول بنجاح',
  'logout': 'تسجيل الخروج',
  'Basics': 'الأساسية',
  'dashboard': 'لوحة التحكم',
  'orders': 'طلباتي',
  'savedCars': 'السيارات المحفوظة',
  'newCars': 'سيارات جديدة',
  'Compare': 'مقارنة',
  'about': 'معلومات عنا',
  'Settings': 'الإعدادات',
  'ThemeMode': 'وضع الثيم',
  'Language': 'اللغة',
  'EditProfile': 'تعديل المعلومات',
  'SignOut': 'تسجيل الخروج',
  'Home': 'الرئيسية',
  'Used': 'مستعملة',
  'Sell': 'بيع',
  'Imported': 'مستورد',
  'More': 'المزيد',
  'TradingName': 'الاسم التجاري',
  'CarAgency': 'وكالة سيارات',
  'ConfirmPassword': 'تأكيد كلمة المرور',
  'Description': 'الوصف',
  'AnAgency': 'وكالة متخصصة في ..*',
  'City': 'المدينة',
  'Choose': 'اختر',
  'Damascus': 'دمشق',
  'Aleppo': 'حلب',
  'Homs': 'حمص',
  'Daraa': 'درعا',
  'Latakia': 'اللاذقية',
  'Tartus': 'طرطوس',
  'Idlib': 'إدلب',
  'Deirez-Zor': 'دير الزور',
  'Hasakah': 'الحسكة',
  'Quneitra': 'القنيطرة',
  'Raqqa': 'الرقة',
  'Al-Sweida': 'السويداء',
  'RuralDamascus': 'ريف دمشق',
  'Hama': 'حماة',
  'Street': 'الشارع*',
  'BaghdadStreet': 'شارع بغداد..',
  'location': 'الموقع',
  'IAgree': 'أوافق على شروط وأحكام أجلة',
  'PrivacyPolicy': 'سياسة الخصوصية',
  'and': 'و',
  'Terms': 'الشروط',
  'ofUse': 'الاستخدام',
  'CreateAccount': 'إنشاء حساب',
  'mustAgree': 'يجب الموافقة على الشروط',
  'required': 'هذا الحقل مطلوب',
  'InvalidFormat': 'صيغة غير صحيحة',
  'mustMatch': 'كلمات المرور غير متطابقة',
  'passwordComplexity':
      'يجب أن تحتوي كلمة المرور على حروف كبيرة وصغيرة ورقم ورمز خاص.',
  'FirstName': 'الاسم الأول',
  'LastName': 'اسم العائلة',
  'fNameHolder': 'جون ج.ي',
  'lNameHolder': 'ديو',
  'birthDate': 'تاريخ الميلاد',
  'Gender': 'الجنس',
  'Male': 'ذكر',
  'Female': 'أنثى',
  'Seller': 'بائع',
  'Dealership': 'وكالة بيع',
  'PhoneVerification': 'تأكيد رقم الهاتف',
  'EnterOTP': 'أدخل رمز التحقق المرسل إلى:',
  'Continue': 'متابعة',
  'CodeRequired': 'الرمز مطلوب',
  'Confirmed': 'تم التأكيد',
  'codeMustBe': 'الرمز يجب أن يكون 4 أرقام.',
  'DidnCode': 'لم يصلك الرمز؟',
  'Resend': 'إعادة الإرسال',
  'CodeSent': 'تم إرسال الرمز بنجاح',
  'NoNumber': 'لا يوجد رقم هاتف',
  "ChooseDate": "إختر تاريخ",
  "Cancel": "إلغاء",
  "Confirm": "تأكيد",
  "SuccessfullyCompleted": "تمت العملية بنجاح",
  "PasswordStrength": "قوة كلمة المرور",
  "Strong": "قوية",
  "Medium": "متوسطة",
  "Weak": "ضعيفة",
  "ResetPassword": "إعادة تعيين كلمة المرور",
  "SendCode": "إرسال رمز التحقق",
  "PassBe": 'لا يمكن أن تكون "password" أو "123"',
};
