const Map<String, String> enUs = {
  'WelcomeBack': 'Welcome Back',
  'login': 'Login',
  'email': 'Email',
  'phone': 'Phone',
  'password': 'Password',
  'or': 'Or',
  'RememberMe': 'Remember me',
  'ForgotPassword': 'Forgot Password ?',
  'invalidEmail': 'Invalid email format',
  'enterPassword': 'Please enter your password',
  'shortPassword': 'Password must be at least 8 characters',
  'dontHaveAccount': "Don't have an account ?",
  'Signup': "Signup",
  'ConfirmAccount': "Confirm Account",
  'register': "Let's get you started",
  'name': 'Name',
  'alreadyHaveAccount': 'Already have an account?',
  'registeredSuccessfully': 'Registered successfully!',
  'loggedSuccessfully': 'You have been logged in successfully',
  'logout': 'Logout',
  'Basics': 'Basics',
  'dashboard': 'My Dashbaord',
  'orders': 'My Orders',
  'savedCars': 'Saved Cars',
  'newCars': 'New Cars',
  'Compare': 'Compare',
  'about': 'About Us',
  'Settings': 'Settings',
  'ThemeMode': 'Theme Mode',
  'Language': 'Language',
  'EditProfile': 'Edit Profile',
  'SignOut': 'SignOut',
  "Home": "Home",
  "Used": "Used",
  "Sell": "Sell",
  "Imported": "Imported",
  "More": "More",
  "TradingName": "Trading Name",
  "CarAgency": "Car agency",
  'ConfirmPassword': 'Confirm Password',
  "Description": "Description",
  "AnAgency": "An agency specialized in ..*",
  "City": "City",
  "Choose": "Choose",
  "Damascus": "Damascus",
  "Aleppo": "Aleppo",
  "Homs": "Homs",
  "Daraa": "Daraa",
  "Latakia": "Latakia",
  "Tartus": "Tartus",
  "Idlib": "Idlib",
  "Deirez-Zor": "Deirez-Zor",
  "Hasakah": "Hasakah",
  "Quneitra": "Quneitra",
  "Raqqa": "Raqqa",
  "Al-Sweida": "Al-Sweida",
  "RuralDamascus": "RuralDamascus",
  "Hama": "Hama",
  "Street": "Street*",
  "BaghdadStreet": "Baghdad Street..",
  "location": "Location",
  "IAgree": "I Agree to Ajaleh’s",
  "PrivacyPolicy": "Privacy Policy",
  "and": "and",
  "Terms": "Terms",
  "ofUse": "of Use",
  "CreateAccount": "Create Account",
  "mustAgree": "You must agree to the terms",
  "required": "This field is required",
  "InvalidFormat": "Invalid input format",
  "mustMatch": "Password does not match",
  "passwordComplexity":
      "Password must contain uppercase and lowercase letters, a number, and a special character.",
  "FirstName": "First Name",
  "LastName": "Last Name",
  "fNameHolder": "John.g.e",
  "lNameHolder": "Deo",
  "birthDate": "Birth Date",
  "Gender": "Gender",
  "Male": "Male",
  "Female": "Female",
  "Seller": "Seller",
  "Dealership": "Dealership",
  "PhoneVerification": "Phone Number Verification",
  "EnterOTP": "Enter OTP sent to:",
  "Continue": "Continue",
  "CodeRequired": "Code is required",
  "Confirmed": "Confirmed",
  "codeMustBe": "code must be 4 digits.",
  "DidnCode": "Didn’t get the code?",
  "Resend": "Resend",
  "CodeSent": "Code has been sent successfully",
  "NoNumber": "There is no phone number",
  "ChooseDate": "Choose Date",
  "Cancel": "Cancel",
  "Confirm": "Confirm",
  "SuccessfullyCompleted": "Successfully completed",
  "PasswordStrength": "Password Strength",
  "Strong": "Strong",
  "Medium": "Medium",
  "Weak": "Weak",
  "ResetPassword": "Reset Password",
  "SendCode": "Send Verification Code",
  "PassBe": 'Cannot be "password" or "123"',
  "UnexpectedError": "Unexpected error",
  "driveDeals": "Drive Deals",
  "sellFase": "Sell Fast",
  "findYourCar": "Find your special Car",
  "resetFilters": "Reset Filters",
  "advancedFilter": "Advanced Filter",
  "moreDeals": "View More Deals",
  "newDeals": "Car New Deals",
  "RentDeals": "Car Rent Deals",
  "ImportDeals": "Car Import Deals",
  "brandShow": "Show Brands",
  "brandHide": "Hide Brands",
  "Search": "Search",
  "YouControl": "You're in control",
  "chooseHow": "choose how you",
  "wantSell": "want to sell your car.",
  "SellCar": "Sell your car",
  "BasicInfo": "Basic Info",
  "MyCars": "My Cars",
  "Messages": "Messages",
  "UsedCars": "Used Cars",
  "ImportedCars": "Imported Cars",
  "RentCars": "Rent Cars",
  "ContactUs": "Contact us",
  "Reviews": "Reviews",
  "FAQ": "FAQ",
  "ajalah": "Ajalah",
  "Save": "Save",
  "SelectMyLocation": "Select my Location",
  "SelectFromMap": "Select location from map",
  "EnableLocationService": "Please enable location service",
  "SiteAccessDenied": "Site access denied",
  "SiteDenied":
      "Site permission has been permanently denied, please change your settings",
  "ChooseFromMap": "Choose from map",
  "SiteSelected": "Site Selected",
};
